# fly.toml file generated on 2023-01-27T17:09:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'cdg'

[build]

[[vm]]
  size = 'shared-cpu-1x'